plugins {
    id 'com.android.application'
}

android {
    namespace 'com.damage.factcheckhud'
    compileSdk 34

    signingConfigs {
        permanent {
            storeFile file(System.getenv('ANDROID_KEYSTORE_PATH') ?: 'missing.jks')
            storePassword System.getenv('ANDROID_KEYSTORE_PASSWORD')
            keyAlias System.getenv('ANDROID_KEY_ALIAS') ?: 'rokid-release'
            keyPassword System.getenv('ANDROID_KEY_PASSWORD')
        }
    }

    defaultConfig {
        applicationId 'com.damage.factcheckhud'
        minSdk 28
        targetSdk 34
        versionCode 101
        versionName '1.1.0-rokid'
    }

    buildTypes {
        release {
            signingConfig signingConfigs.permanent
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        pickFirst 'lib/arm64-v8a/libr2aud.so'
        pickFirst 'lib/armeabi-v7a/libr2aud.so'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation ('com.rokid.security:glass3.open.sdk:2.2.0-E') {
        exclude group: 'org.slf4j'
    }
}
